# Generated by Django 2.1.7 on 2019-02-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='time_ended',
        ),
        migrations.AddField(
            model_name='game',
            name='height',
            field=models.IntegerField(default=7),
        ),
        migrations.AddField(
            model_name='game',
            name='width',
            field=models.IntegerField(default=7),
        ),
    ]
