# Generated by Django 2.1.7 on 2019-03-02 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='time_ended',
            field=models.DateTimeField(null=True),
        ),
    ]
