# Generated by Django 2.1.7 on 2019-03-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_game_time_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='snake_name',
            field=models.CharField(max_length=21, null=True),
        ),
    ]
